#!/usr/bin/env node
// Turns environment variables into public/config.generated.js at deploy time.
//
// The host runs this as part of the build, so settings live in the host's
// environment rather than in this (public) repository, and every device that
// opens the site is configured the moment it loads.
//
// For local work, drop the same keys in a gitignored config.local.json.

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const outPath = resolve(root, 'public/config.generated.js');
const localPath = resolve(root, 'config.local.json');

function readLocal() {
  try {
    return JSON.parse(readFileSync(localPath, 'utf8'));
  } catch {
    return {};
  }
}

function env(name) {
  const value = process.env[name];
  return typeof value === 'string' && value.trim() ? value.trim() : undefined;
}

function list(name) {
  const raw = env(name);
  if (!raw) return undefined;
  return raw
    .split(/[\n,]/)
    .map((s) => s.trim())
    .filter(Boolean);
}

function number(name) {
  const raw = env(name);
  if (raw === undefined) return undefined;
  const value = Number(raw);
  return Number.isFinite(value) ? value : undefined;
}

function defined(object) {
  const out = Object.fromEntries(Object.entries(object).filter(([, v]) => v !== undefined));
  return Object.keys(out).length ? out : undefined;
}

const local = readLocal();

const config = defined({
  boardTitle: env('BOARD_TITLE') ?? local.boardTitle,
  familyName: env('FAMILY_NAME') ?? local.familyName,
  weekStartsOn: number('WEEK_STARTS_ON') ?? local.weekStartsOn,
  familyNames: list('FAMILY_NAMES') ?? local.familyNames,
  weather: defined({
    enabled: env('WEATHER_ENABLED') === undefined ? undefined : env('WEATHER_ENABLED') !== 'false',
    latitude: number('WEATHER_LATITUDE'),
    longitude: number('WEATHER_LONGITUDE'),
    label: env('WEATHER_LABEL'),
    timezone: env('WEATHER_TIMEZONE'),
  }) ?? local.weather,
}) ?? {};

const banner = `// Generated by tools/build-config.mjs at ${new Date().toISOString()}. Do not edit; do not commit.`;
writeFileSync(outPath, `${banner}\nwindow.__MRCL__ = ${JSON.stringify(config, null, 2)};\n`, 'utf8');

console.log(`[build-config] wrote public/config.generated.js (${config.familyNames?.length ?? 0} family name(s))`);

// Calendar addresses are deliberately absent: they are secrets, so they stay in
// the server's environment and never reach the browser.
if (!env('CALENDAR_ICS_URLS')) {
  console.warn('[build-config] CALENDAR_ICS_URLS is not set. The board will work, but nothing will feed it automatically — which is the thing that stopped the last version being used. See docs/DEPLOY.md §2.');
}
