#!/usr/bin/env node
// Turns environment variables into public/config.generated.js at deploy time.
//
// Netlify runs this as the build command, so the Firebase keys live in the
// Netlify UI rather than in this (public) repository, and every device that
// opens the site is configured the moment it loads.
//
// For local work, drop the same keys in a gitignored config.local.json.

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const outPath = resolve(root, 'public/config.generated.js');
const localPath = resolve(root, 'config.local.json');

function readLocal() {
  try {
    return JSON.parse(readFileSync(localPath, 'utf8'));
  } catch {
    return {};
  }
}

function env(name) {
  const value = process.env[name];
  return typeof value === 'string' && value.trim() ? value.trim() : undefined;
}

function firebaseFromEnv() {
  // One JSON blob is the least error-prone thing to paste into Netlify, so it
  // wins if it is present and parseable.
  const blob = env('FIREBASE_CONFIG');
  if (blob) {
    try {
      return JSON.parse(blob);
    } catch (error) {
      console.warn(`[build-config] FIREBASE_CONFIG is not valid JSON (${error.message}); falling back to the individual variables.`);
    }
  }

  const fields = {
    apiKey: env('FIREBASE_API_KEY'),
    authDomain: env('FIREBASE_AUTH_DOMAIN'),
    projectId: env('FIREBASE_PROJECT_ID'),
    storageBucket: env('FIREBASE_STORAGE_BUCKET'),
    messagingSenderId: env('FIREBASE_MESSAGING_SENDER_ID'),
    appId: env('FIREBASE_APP_ID'),
  };
  const present = Object.fromEntries(Object.entries(fields).filter(([, v]) => v !== undefined));
  return Object.keys(present).length ? present : undefined;
}

function list(name) {
  const raw = env(name);
  if (!raw) return undefined;
  return raw
    .split(/[\n,]/)
    .map((s) => s.trim())
    .filter(Boolean);
}

function number(name) {
  const raw = env(name);
  if (raw === undefined) return undefined;
  const value = Number(raw);
  return Number.isFinite(value) ? value : undefined;
}

function defined(object) {
  const out = Object.fromEntries(Object.entries(object).filter(([, v]) => v !== undefined));
  return Object.keys(out).length ? out : undefined;
}

const local = readLocal();

const config = defined({
  boardTitle: env('BOARD_TITLE') ?? local.boardTitle,
  familyName: env('FAMILY_NAME') ?? local.familyName,
  weekStartsOn: number('WEEK_STARTS_ON') ?? local.weekStartsOn,
  firebase: firebaseFromEnv() ?? local.firebase,
  collection: env('FIRESTORE_COLLECTION') ?? local.collection,
  calendars: list('CALENDAR_ICS_URLS') ?? local.calendars,
  weather: defined({
    enabled: env('WEATHER_ENABLED') === undefined ? undefined : env('WEATHER_ENABLED') !== 'false',
    latitude: number('WEATHER_LATITUDE'),
    longitude: number('WEATHER_LONGITUDE'),
    label: env('WEATHER_LABEL'),
    timezone: env('WEATHER_TIMEZONE'),
  }) ?? local.weather,
}) ?? {};

const banner = `// Generated by tools/build-config.mjs at ${new Date().toISOString()}. Do not edit; do not commit.`;
writeFileSync(outPath, `${banner}\nwindow.__MRCL__ = ${JSON.stringify(config, null, 2)};\n`, 'utf8');

const source = config.firebase ? (env('FIREBASE_CONFIG') || env('FIREBASE_API_KEY') ? 'environment' : 'config.local.json') : 'nothing';
console.log(`[build-config] wrote public/config.generated.js (Firebase from ${source}, ${config.calendars?.length ?? 0} calendar feed(s))`);

if (!config.firebase) {
  console.warn('[build-config] No Firebase configuration found. The site will build and load, but will show its setup message instead of the board. See docs/DEPLOY.md.');
}
