#!/usr/bin/env node
// Turns environment variables into public/config.generated.js at deploy time.
//
// Netlify runs this as the build command, so the calendar addresses live in the
// Netlify UI rather than in this (public) repository, and every device that
// opens the site is configured the moment it loads.
//
// For local work, drop the same keys in a gitignored config.local.json.

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const outPath = resolve(root, 'public/config.generated.js');
const localPath = resolve(root, 'config.local.json');

function readLocal() {
  try {
    return JSON.parse(readFileSync(localPath, 'utf8'));
  } catch {
    return {};
  }
}

function env(name) {
  const value = process.env[name];
  return typeof value === 'string' && value.trim() ? value.trim() : undefined;
}

/**
 * CALENDAR_ICS_URLS is either a plain comma/newline separated list of ICS
 * URLs, or JSON for the richer form: [{ url, category, label }].
 */
function calendarsFromEnv() {
  const raw = env('CALENDAR_ICS_URLS');
  if (!raw) return undefined;

  if (raw.trim().startsWith('[')) {
    try {
      const parsed = JSON.parse(raw);
      if (Array.isArray(parsed)) return parsed;
    } catch (error) {
      console.warn(`[build-config] CALENDAR_ICS_URLS looks like JSON but did not parse (${error.message}); reading it as a plain list.`);
    }
  }

  return raw.split(/[\n,]/).map((s) => s.trim()).filter(Boolean);
}

function list(name) {
  const raw = env(name);
  if (!raw) return undefined;
  return raw
    .split(/[\n,]/)
    .map((s) => s.trim())
    .filter(Boolean);
}

function number(name) {
  const raw = env(name);
  if (raw === undefined) return undefined;
  const value = Number(raw);
  return Number.isFinite(value) ? value : undefined;
}

function defined(object) {
  const out = Object.fromEntries(Object.entries(object).filter(([, v]) => v !== undefined));
  return Object.keys(out).length ? out : undefined;
}

const local = readLocal();

const config = defined({
  boardTitle: env('BOARD_TITLE') ?? local.boardTitle,
  familyName: env('FAMILY_NAME') ?? local.familyName,
  weekStartsOn: number('WEEK_STARTS_ON') ?? local.weekStartsOn,
  calendars: calendarsFromEnv() ?? local.calendars,
  familyNames: list('FAMILY_NAMES') ?? local.familyNames,
  weather: defined({
    enabled: env('WEATHER_ENABLED') === undefined ? undefined : env('WEATHER_ENABLED') !== 'false',
    latitude: number('WEATHER_LATITUDE'),
    longitude: number('WEATHER_LONGITUDE'),
    label: env('WEATHER_LABEL'),
    timezone: env('WEATHER_TIMEZONE'),
  }) ?? local.weather,
}) ?? {};

const banner = `// Generated by tools/build-config.mjs at ${new Date().toISOString()}. Do not edit; do not commit.`;
writeFileSync(outPath, `${banner}\nwindow.__MRCL__ = ${JSON.stringify(config, null, 2)};\n`, 'utf8');

console.log(
  `[build-config] wrote public/config.generated.js (${config.calendars?.length ?? 0} calendar feed(s), ${config.familyNames?.length ?? 0} family name(s))`,
);

if (!config.calendars?.length) {
  console.warn('[build-config] No calendar feeds configured. The board will work, but it will only show what is added by hand — which is the thing that stopped the last version being used. See docs/DEPLOY.md §2.');
}
